### ISSUE TITLE
Updating domains does not save them

### ISSUE THREAD

**Issue by Rage65** [ctih1/frii.site-frontend#181] opened 2024-09-19 18:59 UTC
**Describe the bug**
If you update the value of a subdomain then try to save it it says sucsuess but apon refresh of the dashboard it shows the old value. 

**To Reproduce**
update a subdomain
save
refresh

**Expected behavior**
When saving a domain it should commit to the database and stay on the new value even apon refresh of the dashboard

**Additional information:**
Device details 
Windows 10 
Firefox (x64)
DNS 1.1.1.1 and 8.8.8.8

**Comment by ctih1** [comment] 2024-09-19 19:36
Does this happen with every domain, or just one?

**Comment by ctih1** [comment] 2024-09-19 19:38
## A temporary fix
To fix this issue (atleast temporarily), re-register your domain

**Comment by Ponk446** [comment] 2024-10-05 20:40
Had the same problem, the temp fix helps.

**Comment by ctih1** [comment] 2024-10-05 21:09
Fixed in Dev.

Heres a rough sketch on what is going on

![image](https://github.com/user-attachments/assets/4c88ca27-538f-438a-a618-be0619af81bb)

**Comment by ctih1** [comment] 2024-10-05 21:11
TL;DR: Uses wrong schema for database (caused by incorrect function call)

**Comment by ctih1** [comment] 2024-10-10 18:31
task: implement auto fix for corrupted domains

**Comment by ctih1** [comment] 2024-10-17 18:20
Fixed in Dev (canary.frii.site)

**Closed by ctih1** 2024-10-17 18:21 UTC
Labels: bug
